name: Use Auto Assign

on:
  pull_request:
    types: [opened,synchronize]

permissions: 
  pull-requests: write

jobs:
  auto-assign:
    uses: su600/Template/.github/workflows/auto-assign-reviewer.yml@main
    with:
      reviewer: su600